allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - generate-license-file@4.2.1
