#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🧾  Generating third-party license file..."
pnpx generate-license-file --input ./package.json --output ./third-party-licenses.txt --overwrite

git add ./third-party-licenses.txt