# ============================================================================
# Silva 配置文件示例
# ============================================================================
# 使用说明
# 1. 复制此文件并重命名为 `SilvaConfig.yaml`
# 2. 根据需要修改配置项
# 3. 应用会自动读取 SilvaConfig.yaml 文件
# ============================================================================

# ----------------------------------------------------------------------------
# 网站信息配置
# ----------------------------------------------------------------------------
site:
  # 网站所有者名称
  author: 作者

# ----------------------------------------------------------------------------
# 备案信息配置
# ----------------------------------------------------------------------------

registration:
  # ICP 备案
  - name: "京ICP备xxxxxxxx号"
    url: "https://beian.miit.gov.cn/"

  # 公安备案
  - name: "京公网安备xxxxxxxx号"
    url: "http://www.beian.gov.cn/portal/registerSystemInfo"
